### PR TITLE
Add cross_cols for applying logic per row and col

### PR DESCRIPTION
**Pull request by bz2**
For now list of columns in sheet must still be exhaustive, but avoid
repeating triples lines for each column in this case. Also add
conditional that allows for logic on the cell contents but can give
column name as the result value.

### CODE REVIEW

**Review by alightwing — CHANGES_REQUESTED** [review]
The code looks fine on a basic "will execute successfully" level. I have an objection, though, in that I have little idea *why* this change is being made. Without knowing the intended use case, all it looks like it's doing is increasing complexity in exchange for ???.

Also this is going to make the numbers in `make coverage` go down thanks to untested additions to `field` and `trans`, which we should try to avoid.

**Comment by bz2** [comment]
@alightwing Thanks for review!

Yes, this is very much a "first shape of thing that I'm not sure what shape it should take".

The case being addressed here is where the sheet is not a tidy table, but a big sparse matrix with cells representing edges. It's possible to spell this with the current code by writing out a line in triples for each vertex-column, but that still has the issue of needing to check the cell value, but _use_ the column heading.

I suspect spelling this as a kind of unpivot function that then presents the data as reconstructed rows for the triples iteration might be the right way, but I'm not sure on how that should be encoded for the transform file.

**Comment by bz2** [comment]
See for example, `melt()` in pandas:
https://dfrieds.com/data-analysis/melt-unpivot-python-pandas.html

**Comment by alightwing** [comment]
@bz2 I have some thoughts on this (essentially I think your unpivot suggestion is the way to go here, doing a pass to repackage the data and then again to do the triples) but we can discuss when I'm back in the office. For now, I think what you've done is the quickest approach with the existing code.

**Review by alightwing — APPROVED** [review]

**Comment by bz2** [comment]
@alightwing Have added an underscore prefix as mild discouragement, and lets revisit the unpivot topic later.

**Pull request merged**
